package ru.plumsoftware.sudoku.ui.theme

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF004DA3)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFF0071E8)
internal val onPrimaryContainerLight = Color(0xFFFFFFFF)
internal val secondaryLight = Color(0xFF40692A)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFF7EAB64)
internal val onSecondaryContainerLight = Color(0xFF041500)
internal val tertiaryLight = Color(0xFF895100)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFDF8A15)
internal val onTertiaryContainerLight = Color(0xFF1B0C00)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFF9F9FF)
internal val onBackgroundLight = Color(0xFF181C23)
internal val surfaceLight = Color(0xFFF9F9FF)
internal val onSurfaceLight = Color(0xFF181C23)
internal val surfaceVariantLight = Color(0xFFDDE2F3)
internal val onSurfaceVariantLight = Color(0xFF414754)
internal val outlineLight = Color(0xFF717786)
internal val outlineVariantLight = Color(0xFFC1C6D6)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2D3038)
internal val inverseOnSurfaceLight = Color(0xFFEFF0FB)
internal val inversePrimaryLight = Color(0xFFACC7FF)
internal val surfaceDimLight = Color(0xFFD8D9E4)
internal val surfaceBrightLight = Color(0xFFF9F9FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF1F3FE)
internal val surfaceContainerLight = Color(0xFFECEDF8)
internal val surfaceContainerHighLight = Color(0xFFE6E8F2)
internal val surfaceContainerHighestLight = Color(0xFFE0E2ED)

internal val primaryDark = Color(0xFFACC7FF)
internal val onPrimaryDark = Color(0xFF002F67)
internal val primaryContainerDark = Color(0xFF006DE1)
internal val onPrimaryContainerDark = Color(0xFFFFFFFF)
internal val secondaryDark = Color(0xFFA5D488)
internal val onSecondaryDark = Color(0xFF123800)
internal val secondaryContainerDark = Color(0xFF557F3E)
internal val onSecondaryContainerDark = Color(0xFFFFFFFF)
internal val tertiaryDark = Color(0xFFFFB86B)
internal val onTertiaryDark = Color(0xFF492900)
internal val tertiaryContainerDark = Color(0xFFA86500)
internal val onTertiaryContainerDark = Color(0xFFFFFFFF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF10131B)
internal val onBackgroundDark = Color(0xFFE0E2ED)
internal val surfaceDark = Color(0xFF10131B)
internal val onSurfaceDark = Color(0xFFE0E2ED)
internal val surfaceVariantDark = Color(0xFF414754)
internal val onSurfaceVariantDark = Color(0xFFC1C6D6)
internal val outlineDark = Color(0xFF8B90A0)
internal val outlineVariantDark = Color(0xFF414754)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE0E2ED)
internal val inverseOnSurfaceDark = Color(0xFF2D3038)
internal val inversePrimaryDark = Color(0xFF005BBE)
internal val surfaceDimDark = Color(0xFF10131B)
internal val surfaceBrightDark = Color(0xFF363941)
internal val surfaceContainerLowestDark = Color(0xFF0B0E15)
internal val surfaceContainerLowDark = Color(0xFF181C23)
internal val surfaceContainerDark = Color(0xFF1C2027)
internal val surfaceContainerHighDark = Color(0xFF272A32)
internal val surfaceContainerHighestDark = Color(0xFF32353D)

internal val redContainer = Color(0xFFC83232)
internal val onRedContainer = Color(0xFFFFFFFF)
internal val redLeadingContainer = Color(0xFFAC2424)
internal val redShadow = Color(0xFF8A3434)

internal val blueContainer = Color(0xFF5858D4)
internal val onBlueContainer = Color(0xFFFFFFFF)
internal val blueLeadingContainer = Color(0xFF3B3DC8)
internal val blueShadow = Color(0xFF343D8A)

internal val exitContainer = Color(0xFF727272)
internal val onExitContainer = Color(0xFFFFFFFF)
internal val exitLeadingContainer = Color(0xFF4C4C4C)
internal val exitShadow = Color(0xFF3A3A3D)

internal val yellowContainer = Color(0xFFE0C600)
internal val onYellowContainer = Color(0xFF9A967C)
internal val yellowLeadingContainer = Color(0xFFFFC107)
internal val yellowShadow = Color(0xFF9E942A)

internal val gridColor = Color(0xFFF0E9C6)
internal val defaultUserGrid = Color(0xFFBADDF9)
internal val defaultFullGrid = Color(0xFFC4C0B5)